### ISSUE TITLE
TCPPING failed accepting connect from peer

### ISSUE THREAD

**Issue by rmatulis** [zhangliqiang/keycloak-cluster-setup-and-configuration#6]
Hi,

I have setup the TCPPING and it finds the other host no issues but constantly had this in the logs:

> ` 00:29:30,598 WARN  [org.jgroups.protocols.TCP] (TcpServer.Acceptor[7600]-5,null,null) JGRP000006: failed accepting connection from peer: java.io.EOFException
> 	at java.io.DataInputStream.readFully(DataInputStream.java:197)
> 	at org.jgroups.blocks.cs.TcpConnection.readPeerAddress(TcpConnection.java:240)
> 	at org.jgroups.blocks.cs.TcpConnection.<init>(TcpConnection.java:53)
> 	at org.jgroups.blocks.cs.TcpServer$Acceptor.handleAccept(TcpServer.java:126)
> 	at org.jgroups.blocks.cs.TcpServer$Acceptor.run(TcpServer.java:111)
> 	at org.jboss.as.clustering.jgroups.ClassLoaderThreadFactory.lambda$newThread$0(ClassLoaderThreadFactory.java:52)
> 	at java.lang.Thread.run(Thread.java:748)`

here is it finding the other host:

> `00:29:05,329 INFO  [org.infinispan.CLUSTER] (MSC service thread 1-5) ISPN000094: Received new cluster view for channel ejb: [idp|0] (1) [idp]
> 00:29:05,330 INFO  [org.infinispan.CLUSTER] (MSC service thread 1-3) ISPN000094: Received new cluster view for channel ejb: [idp|0] (1) [idp]
> 00:29:05,333 INFO  [org.infinispan.CLUSTER] (MSC service thread 1-8) ISPN000094: Received new cluster view for channel ejb: [idp|0] (1) [idp]
> 00:29:05,333 INFO  [org.infinispan.CLUSTER] (MSC service thread 1-6) ISPN000094: Received new cluster view for channel ejb: [idp|0] (1) [idp]
> 00:29:05,333 INFO  [org.infinispan.CLUSTER] (MSC service thread 1-7) ISPN000094: Received new cluster view for channel ejb: [idp|0] (1) [idp]
> 00:29:05,341 INFO  [org.infinispan.remoting.transport.jgroups.JGroupsTransport] (MSC service thread 1-3) ISPN000079: Channel ejb local address is idp, physical addresses are [192.168.0.1:7600]
> 00:29:05,341 INFO  [org.infinispan.remoting.transport.jgroups.JGroupsTransport] (MSC service thread 1-7) ISPN000079: Channel ejb local address is idp, physical addresses are [192.168.0.1:7600]
> 00:29:05,343 INFO  [org.infinispan.remoting.transport.jgroups.JGroupsTransport] (MSC service thread 1-5) ISPN000079: Channel ejb local address is idp, physical addresses are [192.168.0.1:7600]
> 00:29:05,343 INFO  [org.infinispan.remoting.transport.jgroups.JGroupsTransport] (MSC service thread 1-6) ISPN000079: Channel ejb local address is idp, physical addresses are [192.168.0.1:7600]
> 00:29:05,345 INFO  [org.infinispan.remoting.transport.jgroups.JGroupsTransport] (MSC service thread 1-8) ISPN000079: Channel ejb local address is idp, physical addresses are [192.168.0.1:7600]`

**Comment by rmatulis** [comment]
Issue was due to internetwork firewall
